### ISSUE TITLE
Checklist wagon

### ISSUE THREAD

**Issue by geoffroymart** [sandradc/poof#88]
https://kitt.lewagon.com/products/1945
- [ ] naked domain redirected to www
- [ ] title tag exceeds 20 char
- [ ] open graph meta tags are properly set
- [ ] og image has the right dimension (1200 - 630)
